#MySQL ? JPA ??
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    disable-swagger-default-url: false
    operations-sorter: alpha
    persist-authorization: true
  cache:
    disabled: true

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_AK}
      secret-key: ${AWS_S3_SK}
    region:
      static: ap-northeast-2
    stack:
      auto: false